PING_INTERVAL_MS = 30_000
NO_MOVEMENT_THRESHOLD_MIN = 120
NO_MOVEMENT_RADIUS_METRES = 20
LANDMARK_PROXIMITY_METRES = 100
DANGER_WARN_METRES = 200

ZONE_DENSITY_ALERT_PER_KM2 = 50

XP_PER_PING = 10
XP_PER_CHECKIN = 20
XP_PER_MISSION = 50
XP_LEVEL_BASE = 100

JWT_EXPIRY_TOURIST = "8h"
JWT_EXPIRY_AUTHORITY = "12h"
BCRYPT_COST = 12
LOGIN_LOCKOUT_ATTEMPTS_AUTHORITY = 5
LOGIN_LOCKOUT_ATTEMPTS_TOURIST = 10
LOGIN_LOCKOUT_DURATION_MS = 15 * 60 * 1000

CHECKIN_WINDOW_HOURS = 4
